### ISSUE TITLE
Other languages (i.e.: iOS)

### ISSUE THREAD

**Issue by ehlersd** [michaellperry/jinaga#23]
I've been toying with similar models in iOS (and other platforms) for many years now, this is the first time I have seen a clean implementation of it server-side.

Have you thought about what it would take to code a clean iOS client library?

**Comment by michaellperry** [comment]
Jinaga is actually a JavaScript realization of a C# project: Correspondence (https://github.com/michaellperry/correspondence). Correspondence works with Xamarin on iOS. I've launched 1 iOS application using that library so far (Dallas TechFest 2014).

If I were targeting Objective C, I would probably do something similar to Jinaga. If Swift, I would lean toward Correspondence. Jinaga is dynamic, where Correspondence is strongly typed.

I originally started writing Correspondence in Java. I had it working on Android natively, but that was quite a while ago (https://github.com/michaellperry/CorrespondenceAndroid).

**Comment by michaellperry** [comment]
I've documented the Jinaga roadmap, which includes support for iOS and other client platforms.
